// src/partials/carousel.tsx
import works from '@public/works/works.json';
import React, { useState } from 'react';

export default function Carousel({ className }: { className: string }) {
    const [currentSlide, setCurrentSlide] = useState(0);

    function changeSlide(slide: number) {
        if (slide < 0) setCurrentSlide(works.length - 1);
        else {
            if (slide > works.length - 1) setCurrentSlide(0);
            else setCurrentSlide(slide)
        }
    }

    return (
        <div className={"relative " + className}>
            <div className="overflow-hidden relative h-56 rounded-lg sm:h-64 xl:h-80 2xl:h-96">
                {works.map((work, index) => (
                    <div className={"duration-700 ease-in-out " + (currentSlide !== index ? "hidden" : "block")} key={index}>
                        <img src={"works/" + work.image} className="block absolute top-1/2 left-1/2 w-full -translate-x-1/2 -translate-y-1/2" alt={work.title} />
                    </div>
                ))}
            </div>

            {works.map((work, index) => (
                <div key={index} className={"my-4 "+(currentSlide !== index ? "hidden" : "block")}>
                    <h1 className="mx-4">{work.title}</h1>
                    <p className="mx-4 mt-1 mb-6">{work.desc}</p>
                </div>
            ))}

            <div className="flex absolute bottom-0 left-1/2 z-10 space-x-3 -translate-x-1/2">
                {works.map((work, index) => (
                    <React.Fragment>
                        <button
                            key={index}
                            onClick={changeSlide.bind(null, index)}
                            className={"w-6 h-2 rounded-full " + (currentSlide === index ? "bg-shade" : "bg-gray-800")}
                            aria-current={currentSlide === index ? "true" : "false"}
                            aria-label={work.title}
                        ></button>
                    </React.Fragment>
                ))}
            </div>

            <button className="flex absolute top-0 left-0 z-10 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none" onClick={changeSlide.bind(null, currentSlide - 1)}>
                <span className="inline-flex justify-center items-center w-8 h-16 rounded-md sm:w-10 sm:h-20 group-hover:bg-fade dark:group-hover:bg-fade group-focus:outline-none">
                    <i className="w-5 h-5 text-fade group-hover:text-gray-800 sm:w-6 sm:h-6 fas fa-chevron-left leading-6"></i>
                    <span className="hidden">Previous</span>
                </span>
            </button>
            <button className="flex absolute top-0 right-0 z-10 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none" onClick={changeSlide.bind(null, currentSlide + 1)}>
                <span className="inline-flex justify-center items-center w-8 h-16 rounded-md sm:w-10 sm:h-20 group-hover:bg-fade dark:group-hover:bg-fade group-focus:outline-none">
                    <i className="w-5 h-5 text-fade group-hover:text-gray-800 sm:w-6 sm:h-6 fas fa-chevron-right leading-6"></i>
                    <span className="hidden">Next</span>
                </span>
            </button>
        </div>
    )
}

// partials/Carousel.vue
<template>
  <section class="my-12 mx-6">
    <div class="w-full relative flex flex-col">
      <div class="text-center mt-12" data-aos="fade-up">
        <h4 class="text-xl font-bold dark:text-white">{{$t('carousel.heading')}}</h4>
        <div class="h-1 mt-2 bg-blue-500 mx-auto w-1/12"></div>
      </div>
      <div v-for="slide, index in projectSlides" :key="index" :class="'mt-12 ' + [currentSlide != index ? 'hidden' : '']">
        <img :src="slide.images" :alt="slide.title" class="w-2/3 mx-auto mb-4" data-aos="fade-up" />
        <div class="w-full mt-4" data-aos="fade-up">
          <div class="w-full mt-12 flex items-center justify-center" data-aos="fade-up">
            <button
              class="dark:text-white p-4 mr-6 text-lg rounded-r-md"
              @click="prevSlide()"
            >
              <i class="fa-solid fa-chevron-left"></i>
            </button>
            <button
              v-for="project, projIndex in projectSlides" :key="projIndex" :class="'w-3 h-3 rounded-full mx-2 ' + [projIndex == currentSlide ? 'bg-blue-500' : 'bg-gray-500']"
              @click="currentSlide = index"
            ></button>
            <button
              class="ml-6 p-4 dark:text-white text-lg rounded-l-md"
              @click="nextSlide()"
            >
            <i class="fa-solid fa-chevron-right"></i>
          </button>
          </div>
          <h2 class="text-2xl dark:text-white mb-4">{{ slide.title }}</h2>
          <p class="my-4 dark:text-white text-justify">{{ $t(`carousel.projects[${index}]`) }}</p>
          <p class="my-4">
            <span class="dark:text-white mr-2">{{$t('carousel.roles')}}:</span>
            <span v-for="(role, roleIndex) in slide.roles" :key="roleIndex" class="text-blue-500 mx-2">{{ role }}</span>
          </p>
          <div class="break-all mt-4">
            <span v-for="(tag, tagIndex) in slide.tags" :key="tagIndex" :class="'rounded-md bg-gray-200 dark:bg-gray-800 dark:text-white py-1 px-2 ' + [tagIndex == 0 ? 'mr-2' : 'mx-2']">{{
              tag }}</span>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import { Component, Vue } from 'nuxt-property-decorator'
import projects from '@/static/data/projects.json'
import aosMixin from '@/mixins/aos'

@Component({
  mixins: [aosMixin],
})
export default class Carousel extends Vue {
  projectSlides = projects
  currentSlide = 0

  prevSlide() {
    if (this.currentSlide - 1 < 0) {
      this.currentSlide = this.projectSlides.length - 1
    } else {
      this.currentSlide--
    }
  }

  nextSlide() {
    if (this.currentSlide + 1 > this.projectSlides.length - 1) {
      this.currentSlide = 0
    } else {
      this.currentSlide++
    }
  }
}
</script>
