// src/partials/header.tsx
import { useContext, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { ThemeContext } from '@src/contexts/themeContext';

export default function Header() {
    const { theme, setTheme } = useContext(ThemeContext);
    const [isToggled, setIsToggled] = useState(false);
    const headerRef = useRef<HTMLElement>(null);

    const pages = ['Trang chủ', 'Giới thiệu', 'Dịch vụ', 'Liên hệ'];

    useEffect(()    => {
        setIsToggled(theme === 'dark');
    }, []);

    useEffect(() => {
        isToggled ? setTheme('dark') : setTheme('light');
    }, [isToggled])

    return (
        <header ref={headerRef} className="py-4 px-6 sticky absolute top-0 left-0">
            <nav className="flex">
                <ul className="flex mr-auto py-2">
                    <li className="mr-2 flex items-center">
                        <Link href="/" className="flex items-center">
                            <img src="/logo.svg" alt="Logo" className="w-6 h-6" />
                        </Link>
                    </li>
                    {pages.map((page, index) => (
                        <li key={index} className="mx-2 flex items-center hover:text-primary dark:text-white dark:hover:bg-primary rounded-md px-3 py-1">
                            <Link href="/">{page}</Link>
                        </li>
                    ))}
                </ul>
                <ul className="flex ml-auto">
                    <label htmlFor="themeToggle" className="flex items-center cursor-pointer">
                        <div className="relative">
                            <input type="checkbox" id="themeToggle" checked={isToggled} className="sr-only peer" onChange={() => setIsToggled(!isToggled)} />
                            <div className="peer-checked:bg-gray-700 bg-gray-300 w-14 h-8 rounded-full">
                                <i className={"text-black dark:text-white absolute left-2 top-2 w-4 h-4 fas " + (isToggled ? "fa-moon" : "fa-sun translate-x-6")}></i>
                            </div>
                            <div className="peer-checked:translate-x-full absolute bg-white flex w-6 h-6 left-1 top-1 flex items-center justify-center rounded-full transition"></div>
                        </div>
                    </label>
                </ul>
            </nav>
        </header>
    )
}

// partials/Header.vue
<template>
  <header
    class="dark:bg-black dark:text-white sticky top-0 z-1 dark:bg-black bg-white"
  >
    <nav class="flex text-center">
      <li class="p-6 mr-auto">
        <!-- <button @click="$store.commit('toggleSideMenu')">
          <i class="fa-solid fa-bars text-xl"></i>
        </button> -->
        <button @click="isDroppedDown=!isDroppedDown">
          <i v-if="isDroppedDown==false" class="fa-solid fa-globe text-xl w-6"></i>
          <i v-else class="fa-solid fa-times text-xl w-6"></i>
        </button>
      </li>
      <li class="p-6 mx-auto">
        <NuxtLink to="/">
          <img
            v-if="$colorMode.value === 'dark'"
            src="Logo (Dark).svg"
            class="w-8 h-8"
          />
          <img v-else src="Logo (Light).svg" class="w-8 h-8" />
        </NuxtLink>
      </li>
      <li class="p-6 ml-auto">
        <button class="w-8 h-8" @click="toggleDarkMode">
          <i
            v-if="$colorMode.value === 'dark'"
            class="fa-solid fa-moon text-xl"
          ></i>
          <i v-else class="fa-solid fa-sun text-xl"></i>
        </button>
      </li>
    </nav>
    <ul v-if="isDroppedDown" class="absolute top-14 left-6 divide-y divide-dashed divide-white dark:text-white z-1 bg-gray-200 dark:bg-gray-800">
      <li v-for="locale, index in showLocales" :key="index" class="hover:text-blue-500 px-4 py-2">
        <nuxt-link :to="localePath('index', locale.code)">{{locale.name}}</nuxt-link>
      </li>
    </ul>
  </header>
</template>

<script>
import { Component, Vue } from 'nuxt-property-decorator'

@Component
export default class Header extends Vue {
  isDroppedDown = false

  get showLocales() {
    return this.$i18n.locales;
  }

  toggleDarkMode() {
    if (this.$colorMode.preference !== 'dark') {
      this.$colorMode.preference = 'dark'
    } else {
      this.$colorMode.preference = 'light'
    }
  }
}
</script>
