// partials/Footer.vue
<template>
  <footer class="dark:bg-black dark:text-white">
    <nav class="p-6 flex justify-center items-center">
      <ul class="mr-auto flex justify-center items-center">
        <li v-for="info, index in infos" :key="index" :class="'flex justify-center items-center ' + [index == 0 ? 'mr-4' : 'mx-4']">
          <i :class="'mr-2 text-2xl fa-solid ' + info.icon"></i>
          <a class="hover:text-blue-500 dark:hover:text-blue-500 dark:text-white" href="">{{ info.details }}</a>
        </li>
        <li v-for="(soc, index) in socialMedia" :key="index" class="mx-4">
          <a class="hover:text-blue-500" :href="soc.link">
            <i :class="'fa-brands text-2xl ' + soc.icon"></i>
          </a>
        </li>
      </ul>
      <li class="ml-auto">
        <span class="text-sm text-gray-500">MIT @2022</span>
      </li>
    </nav>
  </footer>
</template>

<script>
import { Component, Vue } from 'nuxt-property-decorator'

@Component
export default class Footer extends Vue {
  infos = [
    { details: 'luongxuantrungdung211@gmail.com', icon: 'fa-envelope' },
    { details: '(+84) 093-436-8160', icon: 'fa-square-phone' },
  ]

  socialMedia = [
    {
      icon: 'fa-linkedin',
      link: 'https://www.linkedin.com/in/adrian-luong-3a3a99202/',
    },
    { icon: 'fa-github', link: 'https://github.com/LuongXuanTrungDung' },
  ]
}
</script>

// src/partials/footer.tsx
export default function Footer() {
    const contactInfo = [{
        icon: "fa-envelope-square",
        info: "luongxuantrungdung211@gmail.com"
    }, {
        icon: "fa-phone-square",
        info: "(+84) 093-436-8160"
    }];

    const socialMedia = [{
        icon: "fa-github",
        link: "https://github.com/LuongXuanTrungDung",
    }, {
        icon: "fa-linkedin",
        link: "https://www.linkedin.com/in/adrian-luong-3a3a99202/"
    }];

    return (
        <footer className="py-4 px-6 text-white bg-light dark:bg-dark">
            <nav className="flex">
                <ul className="flex mr-auto py-2">
                    {contactInfo.map((contact, index) => (
                        <li key={index} className="mr-4">
                            <a href="" className="hover:text-shade dark:hover:text-shade">
                                <i className={"mr-1 text-lg fas " + contact.icon}></i>
                                <span className="ml-1">{contact.info}</span>
                            </a>
                        </li>
                    ))}
                    {socialMedia.map((media, index) => (
                        <li key={index} className={index == 0 ? "mr-2" : "ml-2"}>
                            <a href={media.link} className="hover:text-shade dark:hover:text-shade">
                                <i className={"text-lg fab " + media.icon}></i>
                            </a>
                        </li>
                    ))}
                </ul>
                <ul className="flex ml-auto mr-2 items-center">
                    <p className="text-sm">MIT @2022</p>
                </ul>
            </nav>
        </footer>
    );
}
